### ISSUE TITLE
Package Control Installation

### ISSUE THREAD

**Issue by diego898** [r-stein/st-latex-prefix-key#3]
I can't find this package on package control. Is it possible to support installation using it?

**Comment by r-stein** [comment]
I have added it to Package Control https://packagecontrol.io/packages/LaTeXSmartQuotes, but it is an Sublime Text3 only package. So this will not be available for ST2 users.
Are you using ST2 oder ST3?

**Comment by diego898** [comment]
Hey the link you have is for smartquotes (which I also have installed!) but I cant find prefix key

**Comment by r-stein** [comment]
Ah just clicked on the email link and assumed this was smart quotes. I am actually looking forward to add an improved version of this to LaTeXTools (which may take a while) instead of making my own package.

Until then you can just download this package unzip it and put it into your Packages folder `Preferences >> Browse Packages...`.

**Comment by diego898** [comment]
ah ok great! thanks!
